apiVersion: v1
kind: Service
metadata:
  namespace: default
  name: databoss-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 80
      protocol: TCP
  selector:
    app: bitcoin_fiyat
