apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: bitcoin
  namespace: default
spec:
  interval: 10m0s
  path: ./kubernetes/fluxcd/repositories/bitcoin/deploy
  prune: true
  sourceRef:
    kind: GitRepository
    name: bitcoin
